@echo off
echo Starting Minecraft AFK Calculator...
echo.
echo Refreshing PATH and starting application...
powershell -Command "$env:PATH = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User'); dotnet run"
echo.
echo Application stopped. Press any key to close...
pause >nul
